username = input('Введите ваше имя: ')
title1 = input('Первый заголовок заметки: ')
title2 = input('Второй заголовок заметки: ')
title3 = input('Третий заголовок заметки: ')
titles = [title1, title2, title3]
content = input('Описание заметки: ')
status = input('Укажите статус заметки (Активна/Неактивна): ')
created_date = input('Дата создания заметки (в формате хх-хх-хх): ')
issue_date = input('Дата истечения заметки (в формате хх-хх-хх): ')
print('\nУказанные данные')
print('Имя пользователя:', username)
print('Заголовок:', titles)
print('Описание:', content)
print('Статус:', status)
print('Дата создания:', created_date[0:5])
print('Дата истечения:', issue_date[0:5])
